name: neighborgood
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
