// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfBEjfJsAciTpGcTNBhOfE_BDoBi_3FDA',
    appId: '1:319973720219:web:3afc4238d1e2fdde93063e',
    messagingSenderId: '319973720219',
    projectId: 'neighborgood-7d8c8',
    authDomain: 'neighborgood-7d8c8.firebaseapp.com',
    storageBucket: 'neighborgood-7d8c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWtX-BUatsqWbKI1O_LZ9Tin2i3QbDcUo',
    appId: '1:319973720219:android:1d3f70597511e5f393063e',
    messagingSenderId: '319973720219',
    projectId: 'neighborgood-7d8c8',
    storageBucket: 'neighborgood-7d8c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjP25-DMlT08Caq6F8RTiOriA7grG6EEM',
    appId: '1:319973720219:ios:76edaba225d4d46e93063e',
    messagingSenderId: '319973720219',
    projectId: 'neighborgood-7d8c8',
    storageBucket: 'neighborgood-7d8c8.appspot.com',
    iosBundleId: 'com.application.neighborgood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjP25-DMlT08Caq6F8RTiOriA7grG6EEM',
    appId: '1:319973720219:ios:76edaba225d4d46e93063e',
    messagingSenderId: '319973720219',
    projectId: 'neighborgood-7d8c8',
    storageBucket: 'neighborgood-7d8c8.appspot.com',
    iosBundleId: 'com.application.neighborgood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfBEjfJsAciTpGcTNBhOfE_BDoBi_3FDA',
    appId: '1:319973720219:web:24670ebe55379c9e93063e',
    messagingSenderId: '319973720219',
    projectId: 'neighborgood-7d8c8',
    authDomain: 'neighborgood-7d8c8.firebaseapp.com',
    storageBucket: 'neighborgood-7d8c8.appspot.com',
  );
}
